### ISSUE TITLE
Newest Versions does not work on servers (forge 1.20.1)

### ISSUE THREAD

**Issue by gluzzie** [BeansGalaxy/Beans-Backpacks-2#42]
i have had issues with the mod on my server but nothing too major, when a player tries to log on to the server with the last version of the mod (0.7) they get an error message on their screen saying cannot invoke net.minecraft.world.level.itemLie.m_5456_() because "p_41604_" is null. but if they try to refresh and join the server then it works.  the newest version (0.8) doesn't let the server start        

 Crash Report UUID: 0367f992-f17d-4c91-b434-512931b54016
        FML: 47.2
        Forge: net.minecraftforge:47.2.20[08:20:52] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        BeansBackpacks (beansbackpacks) has failed to load correctly
?7java.lang.NoClassDefFoundError: net/minecraft/client/model/geom/ModelLayerLocation
]

Thank you if your seeing this

**Comment by Atmarsde** [comment]
happened to me as well

**Comment by BeansGalaxy** [comment]
Fixed in 20.1-0.10-v2 & 20.2-0.13-v2
